"""update

Revision ID: fe0ef7a60bcd
Revises: 
Create Date: 2026-04-12 14:12:50.617279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe0ef7a60bcd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('skill_id', sa.String(length=64), nullable=False, comment='与 backend/skills/<skill_id> 一致'),
    sa.Column('name', sa.String(length=128), nullable=False, comment='展示名称'),
    sa.Column('subtitle', sa.String(length=256), nullable=True, comment='副标题'),
    sa.Column('description', sa.Text(), nullable=False, comment='列表短描述'),
    sa.Column('detail_markdown', sa.Text(), nullable=True, comment='详情 Markdown'),
    sa.Column('capability_tags', sa.JSON(), nullable=True, comment='核心能力标签 JSON 数组'),
    sa.Column('icon_key', sa.String(length=64), nullable=True, comment='图标 key'),
    sa.Column('is_published', sa.Boolean(), nullable=False, comment='上架：在技能广场展示；下架仅管理端可见'),
    sa.Column('sort_order', sa.Integer(), nullable=False, comment='排序，越小越前'),
    sa.Column('view_count', sa.Integer(), nullable=False, comment='详情浏览次数'),
    sa.Column('like_count', sa.Integer(), nullable=False, comment='点赞数（预留）'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='数据库主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间(软删除)'),
    sa.Column('deleted_by', sa.String(length=36), nullable=True, comment='删除人标识'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_is_published'), 'skills', ['is_published'], unique=False)
    op.create_index(op.f('ix_skills_skill_id'), 'skills', ['skill_id'], unique=True)
    op.create_table('users',
    sa.Column('username', sa.String(length=50), nullable=False, comment='用户名'),
    sa.Column('nickname', sa.String(length=50), nullable=True, comment='昵称/姓名'),
    sa.Column('email', sa.String(length=100), nullable=True, comment='邮箱'),
    sa.Column('phone', sa.String(length=20), nullable=True, comment='手机号'),
    sa.Column('password', sa.String(length=255), nullable=False, comment='密码哈希'),
    sa.Column('user_type', sa.String(length=20), nullable=False, comment='用户类型'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True, comment='最后登录时间'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='数据库主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间(软删除)'),
    sa.Column('deleted_by', sa.String(length=36), nullable=True, comment='删除人标识'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_phone'), 'users', ['phone'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('user_llm_profiles',
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户 ID'),
    sa.Column('provider', sa.String(length=32), nullable=False, comment='模型提供商：openai/deepseek/qwen/zhipu/anthropic/other'),
    sa.Column('display_name', sa.String(length=128), nullable=False, comment='展示名称（下拉中显示）'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('api_base', sa.String(length=512), nullable=False, comment='OpenAI 兼容 API Base，如 https://api.deepseek.com/v1'),
    sa.Column('model_name', sa.String(length=128), nullable=False, comment='模型名，如 deepseek-chat'),
    sa.Column('api_key', sa.Text(), nullable=False, comment='API Key'),
    sa.Column('key_last4', sa.String(length=8), nullable=False, comment='Key 后若干位展示用'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='数据库主键ID'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='更新时间'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='删除时间(软删除)'),
    sa.Column('deleted_by', sa.String(length=36), nullable=True, comment='删除人标识'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_llm_profiles_user_id'), 'user_llm_profiles', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_llm_profiles_user_id'), table_name='user_llm_profiles')
    op.drop_table('user_llm_profiles')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_phone'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_skills_skill_id'), table_name='skills')
    op.drop_index(op.f('ix_skills_is_published'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
